DROP TABLE IF EXISTS PRODUCT_PRICE;

DROP TABLE IF EXISTS PRODUCT;

DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (ID BIGINT IDENTITY , NAME VARCHAR(255) NOT NULL);

CREATE TABLE PRODUCT (ID BIGINT IDENTITY ,
                      NAME VARCHAR(255) NOT NULL,
                      SKU VARCHAR(20) NOT NULL,
                      CATEGORY_ID BIGINT NOT NULL,
                      LAST_UPDATED TIMESTAMP NOT NULL,
FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID) ON UPDATE CASCADE);


CREATE TABLE PRODUCT_PRICE (ID BIGINT IDENTITY ,
                            PRODUCT_ID BIGINT NOT NULL,
                            PRICE DECIMAL(10,2) NOT NULL,
                            PRICE_TYPE VARCHAR(10) NOT NULL,
                            CURRENCY_CODE VARCHAR(3),
                            FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID) ON UPDATE CASCADE);



